"""empty message

Revision ID: 701b48c15f4e
Revises: 81dacd8487f2
Create Date: 2022-10-17 21:30:51.882676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701b48c15f4e'
down_revision = '81dacd8487f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('const_password', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'const_password')
    # ### end Alembic commands ###
